#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.127                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = sh -c -x "gcc
CXX = sh -c -x "g++
AR = sh -c -x "ar
LD = sh -c -x "g++
WINDRES = windres

INC =  -I/usr/include/libxml2 -Iinclude -Ilibusb/libusb
CFLAGS =  -Wall `wx-config --cflags` -Winvalid-pch -include wx_pch.h `python-config --includes` `pkg-config --libs --cflags glib-2.0` -DWX_PRECOMP
RESINC = 
LIBDIR =  -Llibusb/libusb/.libs -Llibusb/libusb
LIB =  -lopenobex -lxml2 -ludev libusb/libusb/.libs/libusb-1.0.a libusb/libusb/.libs/libusb-1.0.so
LDFLAGS =  `wx-config --libs` `python-config --libs` -lglib-2.0 `wx-config --cflags` -Winvalid-pch -include wx_pch.h `pkg-config --libs --cflags glib-2.0`

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -O3 -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR) -Llibusb/libusb
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/LibreScribe

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O3
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/LibreScribe

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/AboutDialog.o $(OBJDIR_DEBUG)/src/DeviceInfo.o $(OBJDIR_DEBUG)/src/GUIFrame.o $(OBJDIR_DEBUG)/src/LibreScribe.o $(OBJDIR_DEBUG)/src/BackgroundMonitor.o $(OBJDIR_DEBUG)/src/Smartpen.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/AboutDialog.o $(OBJDIR_RELEASE)/src/DeviceInfo.o $(OBJDIR_RELEASE)/src/GUIFrame.o $(OBJDIR_RELEASE)/src/LibreScribe.o $(OBJDIR_RELEASE)/src/BackgroundMonitor.o $(OBJDIR_RELEASE)/src/Smartpen.o

all: before_build build_debug build_release after_build

clean: clean_debug clean_release

before_build: 
	cd $(PROJECT_DIRECTORY) && rm -rfv ./bin
	cd $(PROJECT_DIRECTORY)libusb/ && [ -f configure ] || sh autogen.sh
	cd $(PROJECT_DIRECTORY)libusb/ && [ -f Makefile ] || ./configure
	cd $(PROJECT_DIRECTORY)libusb/ && [ -f libusb/.libs/libusb-1.0.a ] || make

after_build: 
	cd $(PROJECT_DIRECTORY)
	find ./bin/ -mindepth 1 -maxdepth 1 -type d | xargs -n 1 cp -rfv -L ./res ./xdg
	find ./bin/ -mindepth 1 -maxdepth 1 -type d | xargs -n 1 cp -fv -L ./stf.py ./convert_stfs.sh

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(OBJ_DEBUG) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)"

$(OBJDIR_DEBUG)/src/AboutDialog.o: src/AboutDialog.cc
	$(CC) -c src/AboutDialog.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/AboutDialog.o"

$(OBJDIR_DEBUG)/src/DeviceInfo.o: src/DeviceInfo.cc
	$(CC) -c src/DeviceInfo.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/DeviceInfo.o"

$(OBJDIR_DEBUG)/src/GUIFrame.o: src/GUIFrame.cc
	$(CC)  -c src/GUIFrame.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/GUIFrame.o"

$(OBJDIR_DEBUG)/src/LibreScribe.o: src/LibreScribe.cc
	$(CC) -c src/LibreScribe.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/LibreScribe.o"

$(OBJDIR_DEBUG)/src/BackgroundMonitor.o: src/BackgroundMonitor.cc
	$(CC) -c src/BackgroundMonitor.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/BackgroundMonitor.o"

$(OBJDIR_DEBUG)/src/Smartpen.o: src/Smartpen.cc
	$(CC) -c src/Smartpen.cc $(CFLAGS_DEBUG) $(INC_DEBUG) -o $(OBJDIR_DEBUG)/src/Smartpen.o"

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(OBJ_RELEASE) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)"

$(OBJDIR_RELEASE)/src/AboutDialog.o: src/AboutDialog.cc
	$(CC) -c src/AboutDialog.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/AboutDialog.o"

$(OBJDIR_RELEASE)/src/DeviceInfo.o: src/DeviceInfo.cc
	$(CC) -c src/DeviceInfo.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/DeviceInfo.o"

$(OBJDIR_RELEASE)/src/GUIFrame.o: src/GUIFrame.cc
	$(CC) -c src/GUIFrame.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/GUIFrame.o"

$(OBJDIR_RELEASE)/src/LibreScribe.o: src/LibreScribe.cc
	$(CC) -c src/LibreScribe.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/LibreScribe.o"

$(OBJDIR_RELEASE)/src/BackgroundMonitor.o: src/BackgroundMonitor.cc
	$(CC) -c src/BackgroundMonitor.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/BackgroundMonitor.o"

$(OBJDIR_RELEASE)/src/Smartpen.o: src/Smartpen.cc
	$(CC) -c src/Smartpen.cc $(CFLAGS_RELEASE) $(INC_RELEASE) -o $(OBJDIR_RELEASE)/src/Smartpen.o"

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release
